apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: series-tracker
  labels:
    app: backend
    app.kubernetes.io/name: series-tracker
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        app.kubernetes.io/name: series-tracker
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: sara583/series-tracker-backend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 4000
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
