apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: series-tracker
  labels:
    app: backend
    app.kubernetes.io/name: series-tracker
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 4000
      targetPort: http
