apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: series-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sara583/series-tracker-backend:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI