apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: series-tracker
  labels:
    app: frontend
    app.kubernetes.io/name: series-tracker
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 5173
      targetPort: http
