apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: series-tracker
  labels:
    app: mongo
    app.kubernetes.io/name: series-tracker
    app.kubernetes.io/component: mongo
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        app.kubernetes.io/name: series-tracker
        app.kubernetes.io/component: mongo
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: mongo
          image: mongo:7
          imagePullPolicy: IfNotPresent
          command:
            - mongod
          args:
            - --bind_ip_all
          ports:
            - name: mongo
              containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
